ALTER TABLE rooms
    ADD COLUMN price NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (price >= 0),
    ADD COLUMN capacity INTEGER NOT NULL DEFAULT 1 CHECK (capacity > 0);

ALTER TABLE rooms ALTER COLUMN price DROP DEFAULT;
ALTER TABLE rooms ALTER COLUMN capacity DROP DEFAULT;

ALTER TABLE cabins
    ADD COLUMN price NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (price >= 0),
    ADD COLUMN capacity INTEGER NOT NULL DEFAULT 1 CHECK (capacity > 0);

ALTER TABLE cabins ALTER COLUMN price DROP DEFAULT;
ALTER TABLE cabins ALTER COLUMN capacity DROP DEFAULT;
