
CREATE TABLE IF NOT EXISTS permissions (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    resource    VARCHAR(50) NOT NULL,
    action      VARCHAR(50) NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_permissions_resource_action UNIQUE (resource, action)
);

INSERT INTO permissions (resource, action, description) VALUES
    ('bookings', 'create', 'Create a new room booking'),
    ('bookings', 'read', 'View bookings'),
    ('bookings', 'update', 'Modify a booking'),
    ('bookings', 'delete', 'Delete a booking'),
    ('bookings', 'checkin', 'Check in a guest'),
    ('bookings', 'checkout', 'Check out a guest'),
    ('bookings', 'cancel', 'Cancel a booking'),
    ('rooms', 'create', 'Add a new room'),
    ('rooms', 'read', 'View rooms'),
    ('rooms', 'update', 'Edit room details'),
    ('rooms', 'delete', 'Remove a room'),
    ('rooms', 'manage_availability', 'Block/unblock room availability'),
    ('orders', 'create', 'Place a food/service order'),
    ('orders', 'read', 'View orders'),
    ('orders', 'update', 'Edit an order'),
    ('orders', 'update_status', 'Change order status'),
    ('orders', 'cancel', 'Cancel an order'),
    ('orders', 'refund', 'Refund an order'),
    ('menu', 'create', 'Add a menu item'),
    ('menu', 'read', 'View the menu'),
    ('menu', 'update', 'Edit a menu item'),
    ('menu', 'delete', 'Remove a menu item'),
    ('kitchen', 'view_queue', 'View kitchen order queue'),
    ('kitchen', 'update_status', 'Update food preparation status'),
    ('kitchen', 'manage_stations', 'Manage kitchen stations/printers'),
    ('tables', 'manage', 'Manage dine-in tables and QR codes'),
    ('inventory', 'create', 'Add inventory items'),
    ('inventory', 'read', 'View inventory'),
    ('inventory', 'update', 'Adjust stock levels'),
    ('inventory', 'delete', 'Remove inventory items'),
    ('payments', 'process', 'Process a payment'),
    ('payments', 'refund', 'Issue a refund'),
    ('payments', 'view', 'View payment records'),
    ('members', 'invite', 'Invite a team member'),
    ('members', 'read', 'View team members'),
    ('members', 'update', 'Edit a team member'),
    ('members', 'remove', 'Remove a team member'),
    ('roles', 'create', 'Create a role'),
    ('roles', 'read', 'View roles'),
    ('roles', 'update', 'Edit a role'),
    ('roles', 'delete', 'Delete a role'),
    ('roles', 'assign', 'Assign a role to a member'),
    ('reports', 'view', 'View reports and analytics'),
    ('reports', 'export', 'Export reports'),
    ('settings', 'manage', 'Manage hotel settings'),
    ('customers', 'read', 'View customer profiles'),
    ('customers', 'update', 'Edit customer profiles'),
    ('conversations', 'read', 'View omnichannel messages (Facebook, Instagram, WhatsApp)'),
    ('conversations', 'reply', 'Reply to guest messages across channels'),
    ('conversations', 'assign', 'Assign a conversation to a staff member'),
    ('conversations', 'manage_channels', 'Connect/disconnect Facebook, Instagram and WhatsApp channels')
ON CONFLICT (resource, action) DO NOTHING;
